version: '3.1'
#indentation is important!

services:
  www:
    image: php:apache
    volumes:
      - ./www:/var/www/html/
    ports:
      - 8000:80
      - 433:433
  db: 
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db 
      - PMA_PORT=3306